"""add cell number

Revision ID: 68ae2156cfa3
Revises: 835291ea998a
Create Date: 2024-12-13 00:22:39.175553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ae2156cfa3'
down_revision: Union[str, None] = '835291ea998a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cell_no', sa.VARCHAR(), nullable=True))
    # op.create_unique_constraint(None, 'users', ['cell_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cell_no')
    # ### end Alembic commands ###
