"""tables created

Revision ID: 945282a23e12
Revises: 
Create Date: 2025-01-21 17:32:21.835650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945282a23e12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('length_in_km', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rivers')
    # ### end Alembic commands ###
